# Laplace equation on the unit disk: watch the VariationalBayesianSolver learn the sources.
#
# The setup is the one of test/variational_test.jl ("ARD with source position updates
# learns the sources"): 10 true sources on a circle of radius 1.1, each with a Gaussian
# amplitude aᵢ ~ N(μᵢ, vᵢ). The boundary data carry the mean field and its variance
#     u(x) = Σᵢ μᵢ G(x - χᵢ),   Var u(x) = Σᵢ vᵢ G(x - χᵢ)²,
# as a vector of MvNormals, one per boundary point. The solver starts from 60 candidate
# sources on a ring of radius 1.35 and, iteration by iteration, moves them (M-step over χ)
# and prunes the ones whose learned prior variance 1/αᵢ collapses (ARD).
#
# Running this file saves, into figures/:
#   sources_iter_###.png  — one frame per snapshot: the field generated by the current
#                           sources, the sources sized by their learned prior std 1/√αᵢ,
#                           the initial candidates, and the true sources;
#   source_learning.gif   — the frames as an animation;
#   field_comparison.png  — the true mean field next to the final learned field.
#
# Needs Plots.jl (not a dependency of this package): julia> include(this file) from an
# environment where `using Plots` works, e.g. the default environment.

using MethodOfFundamentalSolutions
using Distributions, LinearAlgebra, StaticArrays, Statistics, Random
using Plots
gr()

outdir = joinpath(@__DIR__, "figures")
mkpath(outdir)

# ------------------------------------------------------------------ the true sources
medium = LaplaceMedium{2, Float64}()
FT = DirichletType()
Random.seed!(1234)

N_sources = 10
source_θs = LinRange(0, 2pi, N_sources + 1)[1:N_sources] + rand(N_sources) * 0.1
source_pos = [[1.1 * cos(θ), 1.1 * sin(θ)] for θ in source_θs]

# want all amps to same strength, as then they can be learned.
signs = [ θ > pi ? 1.0 : -1.0  for θ in source_θs]
source_amps = (-1.0) .^ signs
source_vars = (0.05 .* source_amps) .^ 2   # a 5% standard deviation per source

# --------------------------------------------------- boundary data with the field variance
N_points = 40
points_θs = LinRange(0, 2pi, N_points + 1)[1:N_points]
points = [[cos(θ), sin(θ)] for θ in points_θs]

# 1) evaluate the field of the combined sources: its mean and its variance
field_mean(x) = sum(source_amps[i] * greens(FT, medium, x - source_pos[i]) for i in eachindex(source_pos))
field_var(x) = sum(source_vars[i] * greens(FT, medium, x - source_pos[i])^2 for i in eachindex(source_pos))

bd = BoundaryData(FT;
    boundary_points = points,
    fields = [MvNormal([field_mean(x)], field_var(x) * I(1)) for x in points]
)

## Below uses the exact induced error covariance matrix. When using it the source positions do not change. 
    # bd = BoundaryData(FT; boundary_points = points) # used just for the system_matrix dispatch
    # M = system_matrix([SVector{2, Float64}(p) for p in source_pos], medium, bd)
    # Σ_induced = Symmetric(M * Diagonal(source_vars) * M' + 1e-9 * I)
    # bd = BoundaryData(FT;
    #     boundary_points = points,
    #     fields = MvNormal(field_mean.(points), Σ_induced)
    # )

# ------------------------------------------------------------------ candidate sources
N_dense = 60
dense_θs = LinRange(0, 2pi, N_dense + 1)[1:N_dense]
sources0 = [[1.35 * cos(θ), 1.35 * sin(θ)] for θ in dense_θs]

solver_upto(k) = VariationalBayesianSolver(
    prior_variance = 1.0,
    optimise_source_positions_flag = true,
    ard_threshold = 1e6,
    max_iters = k,
    elbo_tol = 1e-9
)

# ------------------------------------------------------------------------ plotting
# The interior field heatmap and the retained sources (sized by their learned prior std
# 1/√αᵢ, the ones shrinking being about to be pruned by ARD) come straight from the
# `VariationalSolution`/`FundamentalSolution` + `BoundaryData` plot recipes in plot/plot.jl;
# `bd` supplies both the field type and the disk that masks the heatmap. Here we only add
# the overlays specific to this example: the initial candidates and the true sources.
res = 141                          # grid resolution for the interior heatmaps
plotlims = (-1.55, 1.55)

# the true sources as a FundamentalSolution, so predict_field / the recipe draw their field
fsol_true = FundamentalSolution(medium; positions = source_pos, coefficients = source_amps)

# shared color limits from the true field over the interior of the disk (NaN outside)
fr_true = predict_field(fsol_true, bd; xres = res, yres = res)
clims = extrema(filter(isfinite, first.(field(fr_true))))

marker_true = (:xcross, 7, :black)
color_initial = "#6b7280"

# overlay the initial candidates and the true sources onto an existing field plot
function add_reference_sources!(plt)
    scatter!(plt, [p[1] for p in sources0], [p[2] for p in sources0];
        marker = (:circle, 2.5), markercolor = :white, markerstrokecolor = color_initial,
        label = "initial candidates")
    scatter!(plt, [p[1] for p in source_pos], [p[2] for p in source_pos];
        marker = marker_true, markerstrokewidth = 2, label = "true sources")
    return plt
end

function frame(vsol, k)
    plt = plot(vsol, bd;
        xres = res, yres = res,
        c = :inferno, clims = clims, colorbar_title = "field", legend = true,
        xlims = plotlims, ylims = plotlims,
        title = "iteration $k:  $(length(vsol.fsol.positions)) of $N_dense sources",
        titlefontsize = 11, size = (620, 560), background_color = :white
    )
    return add_reference_sources!(plt)
end

snapshots = [1, 2, 3, 4, 6, 8, 12, 16, 24, 40, 80, 150]
vsol_final = nothing
plts = map(enumerate(snapshots)) do (i, k)
    # the solver is deterministic, so re-solving with max_iters = k reproduces the
    # state of the full run after k iterations
    sim = Simulation(medium, bd; solver = solver_upto(k), source_positions = sources0)
    vsol = solve(sim)
    global vsol_final = vsol
    plt = frame(vsol, k)
    png(plt, joinpath(outdir, "sources_iter_" * lpad(k, 3, '0') * ".png"))
    println("iteration $k: $(length(vsol.fsol.positions)) sources retained")
    plt
end

anim = Animation()
foreach(plt -> Plots.frame(anim, plt), plts)
gif(anim, joinpath(outdir, "source_learning.gif"); fps = 2)

# ------------------------------------------------ the true field next to the learned one
# the FundamentalSolution + BoundaryData recipe draws the true field; sources = false since
# the true positions are drawn below as the xcross markers
plt_true = plot(fsol_true, bd;
    xres = res, yres = res, sources = false,
    c = :amp, clims = clims, colorbar = false,
    xlims = plotlims, ylims = plotlims,
    title = "true mean field", titlefontsize = 11
)
scatter!(plt_true, [p[1] for p in source_pos], [p[2] for p in source_pos];
    marker = marker_true, markerstrokewidth = 2, label = "true sources")

plt_learned = frame(vsol_final, snapshots[end])
plot!(plt_learned, title = "learned field and sources")

plt_cmp = plot(plt_true, plt_learned; layout = (1, 2), size = (1150, 520))
png(plt_cmp, joinpath(outdir, "field_comparison.png"))

println("saved figures to $outdir")
