# Laplace equation on the unit disk: watch the VariationalBayesianSolver learn the sources.
#
# The setup is the one of test/variational_test.jl ("ARD with source position updates
# learns the sources"): 10 true sources on a circle of radius 1.1, each with a Gaussian
# amplitude aᵢ ~ N(μᵢ, vᵢ). The boundary data carry the mean field and its variance
#     u(x) = Σᵢ μᵢ G(x - χᵢ),   Var u(x) = Σᵢ vᵢ G(x - χᵢ)²,
# as a vector of MvNormals, one per boundary point.
#
# Two ways of finding the sources from the same data are run and compared:
#
#   1. "ring"  — 60 candidates on a ring of radius 1.35, `optimise_source_positions_flag =
#      true`. Each iteration both moves the sources (M-step over χ) and prunes the ones
#      whose learned prior variance 1/αᵢ collapses (ARD).
#   2. "grid"  — candidates everywhere outside the disk (`grid_source_positions`), with
#      `optimise_source_positions_flag = false`. The sources never move: ARD alone has to
#      pick out the relevant ones from the fixed dictionary.
#
# The comparison answers the question "can ARD alone learn the sources?": no. See the
# summary printed at the end and the comment above it.
#
# Running this file saves, into figures/:
#   sources_iter_###.png       — one frame per snapshot of case 1: the field generated by
#                                the current sources, the sources sized by their learned
#                                prior std 1/√αᵢ, the initial candidates, the true sources;
#   source_learning.gif        — those frames as an animation;
#   field_comparison.png       — the true mean field next to the final learned field;
#   grid_sources_iter_###.png,
#   grid_source_learning.gif,
#   grid_field_comparison.png  — the same three for case 2;
#   ard_vs_positions.png       — the final sources of both cases side by side.
#
# Needs Plots.jl (not a dependency of this package): julia> include(this file) from an
# environment where `using Plots` works, e.g. the default environment.

using MethodOfFundamentalSolutions
using Distributions, LinearAlgebra, StaticArrays, Statistics, Random
using Plots
gr()

outdir = joinpath(@__DIR__, "figures")
mkpath(outdir)

# ------------------------------------------------------------------ the true sources
medium = LaplaceMedium{2, Float64}()
FT = DirichletType()
Random.seed!(1234)

N_sources = 10
source_θs = LinRange(0, 2pi, N_sources + 1)[1:N_sources] + rand(N_sources) * 0.1
source_pos = [[1.1 * cos(θ), 1.1 * sin(θ)] for θ in source_θs]

# want all amps to same strength, as then they can be learned.
signs = [ θ > pi ? 1.0 : -1.0  for θ in source_θs]
source_amps = (-1.0) .^ signs
source_vars = (0.05 .* source_amps) .^ 2   # a 5% standard deviation per source

# --------------------------------------------------- boundary data with the field variance
N_points = 40
points_θs = LinRange(0, 2pi, N_points + 1)[1:N_points]
points = [[cos(θ), sin(θ)] for θ in points_θs]

# 1) evaluate the field of the combined sources: its mean and its variance
field_mean(x) = sum(source_amps[i] * greens(FT, medium, x - source_pos[i]) for i in eachindex(source_pos))
field_var(x) = sum(source_vars[i] * greens(FT, medium, x - source_pos[i])^2 for i in eachindex(source_pos))

bd = BoundaryData(FT;
    boundary_points = points,
    fields = [MvNormal([field_mean(x)], field_var(x) * I(1)) for x in points]
)

## Below uses the exact induced error covariance matrix. When using it the source positions do not change.
    # bd = BoundaryData(FT; boundary_points = points) # used just for the system_matrix dispatch
    # M = system_matrix([SVector{2, Float64}(p) for p in source_pos], medium, bd)
    # Σ_induced = Symmetric(M * Diagonal(source_vars) * M' + 1e-9 * I)
    # bd = BoundaryData(FT;
    #     boundary_points = points,
    #     fields = MvNormal(field_mean.(points), Σ_induced)
    # )

# ------------------------------------------------------------------ candidate sources
# case 1: a ring just outside the true sources, free to move
N_dense = 60
dense_θs = LinRange(0, 2pi, N_dense + 1)[1:N_dense]
sources_ring = [[1.35 * cos(θ), 1.35 * sin(θ)] for θ in dense_θs]

# case 2: sources everywhere outside the disk, held fixed. `grid_source_positions` lays a
# regular grid over the bounding box of `bd` enlarged by `scale`, dropping the points inside
# the disk and those closer to the boundary than `clearance` times the boundary spacing.
sources_grid = grid_source_positions(bd; n = 15, scale = 1.5, clearance = 0.5)

solver_upto(k; optimise_positions) = VariationalBayesianSolver(
    prior_variance = 1.0,
    optimise_source_positions_flag = optimise_positions,
    ard_threshold = 1e6,
    max_iters = k,
    elbo_tol = 1e-9
)

# ------------------------------------------------------------------------ plotting
# The interior field heatmap and the retained sources (sized by their learned prior std
# 1/√αᵢ, the ones shrinking being about to be pruned by ARD) come straight from the
# `VariationalSolution`/`FundamentalSolution` + `BoundaryData` plot recipes in plot/plot.jl;
# `bd` supplies both the field type and the disk that masks the heatmap. Here we only add
# the overlays specific to this example: the initial candidates and the true sources.
res = 141                          # grid resolution for the interior heatmaps

# the true sources as a FundamentalSolution, so predict_field / the recipe draw their field
fsol_true = FundamentalSolution(medium; positions = source_pos, coefficients = source_amps)

# shared color limits from the true field over the interior of the disk (NaN outside)
fr_true = predict_field(fsol_true, bd; xres = res, yres = res)
clims = extrema(filter(isfinite, first.(field(fr_true))))

marker_true = (:xcross, 7, :black)
color_initial = "#6b7280"

# overlay the initial candidates and the true sources onto an existing field plot
function add_reference_sources!(plt, sources0)
    scatter!(plt, [p[1] for p in sources0], [p[2] for p in sources0];
        marker = (:circle, 2.5), markercolor = :white, markerstrokecolor = color_initial,
        label = "initial candidates")
    scatter!(plt, [p[1] for p in source_pos], [p[2] for p in source_pos];
        marker = marker_true, markerstrokewidth = 2, label = "true sources")
    return plt
end

function frame(vsol, k, sources0, plotlims)
    plt = plot(vsol, bd;
        xres = res, yres = res,
        c = :inferno, clims = clims, colorbar_title = "field", legend = true,
        xlims = plotlims, ylims = plotlims,
        title = "iteration $k:  $(length(vsol.fsol.positions)) of $(length(sources0)) sources",
        titlefontsize = 11, size = (620, 560), background_color = :white
    )
    return add_reference_sources!(plt, sources0)
end

snapshots = [1, 2, 3, 4, 6, 8, 12, 16, 24, 40, 80, 150]

# Solve up to each snapshot and save a frame. The solver is deterministic, so re-solving
# with max_iters = k reproduces the state of the full run after k iterations.
function run_case(sources0; optimise_positions, plotlims, prefix)
    vsol_final = nothing
    plts = map(snapshots) do k
        sim = Simulation(medium, bd;
            solver = solver_upto(k; optimise_positions = optimise_positions),
            source_positions = sources0)
        vsol = solve(sim)
        vsol_final = vsol
        plt = frame(vsol, k, sources0, plotlims)
        png(plt, joinpath(outdir, prefix * "sources_iter_" * lpad(k, 3, '0') * ".png"))
        println("$prefix iteration $k: $(length(vsol.fsol.positions)) sources retained")
        plt
    end

    anim = Animation()
    foreach(plt -> Plots.frame(anim, plt), plts)
    gif(anim, joinpath(outdir, prefix * "source_learning.gif"); fps = 2)

    return vsol_final
end

# the true field next to the learned one; the FundamentalSolution + BoundaryData recipe draws
# the true field with sources = false, since the true positions are the xcross markers below
function save_field_comparison(vsol, sources0, plotlims, filename)
    plt_true = plot(fsol_true, bd;
        xres = res, yres = res, sources = false,
        c = :amp, clims = clims, colorbar = false,
        xlims = plotlims, ylims = plotlims,
        title = "true mean field", titlefontsize = 11
    )
    scatter!(plt_true, [p[1] for p in source_pos], [p[2] for p in source_pos];
        marker = marker_true, markerstrokewidth = 2, label = "true sources")

    plt_learned = frame(vsol, snapshots[end], sources0, plotlims)
    plot!(plt_learned, title = "learned field and sources")

    plt_cmp = plot(plt_true, plt_learned; layout = (1, 2), size = (1150, 520))
    png(plt_cmp, joinpath(outdir, filename))
    return plt_learned
end

# ------------------------------------------------------- case 1: ring, sources free to move
lims_ring = (-1.55, 1.55)
vsol_ring = run_case(sources_ring; optimise_positions = true, plotlims = lims_ring, prefix = "")
plt_ring = save_field_comparison(vsol_ring, sources_ring, lims_ring, "field_comparison.png")

# --------------------------------------- case 2: sources everywhere outside, ARD alone
lims_grid = (-1.65, 1.65)
vsol_grid = run_case(sources_grid; optimise_positions = false, plotlims = lims_grid, prefix = "grid_")
plt_grid = save_field_comparison(vsol_grid, sources_grid, lims_grid, "grid_field_comparison.png")

plot!(plt_ring, title = "ring + position M-step", titlefontsize = 11)
plot!(plt_grid, title = "sources everywhere, ARD only", titlefontsize = 11)
png(plot(plt_ring, plt_grid; layout = (1, 2), size = (1150, 520)),
    joinpath(outdir, "ard_vs_positions.png"))

# ------------------------------------------------------------------------- the comparison
# How well was each case learned? Two numbers per case: the error of the predicted field at
# fresh boundary points halfway between the data points (the data are fitted by construction,
# so only fresh points say anything), and how far each true source is from the nearest
# retained source.
θ_fresh = points_θs .+ (points_θs[2] - points_θs[1]) / 2
field_scale = maximum(abs, field_mean.(points))

function report(name, sources0, vsol)
    errs = map(θ_fresh) do θ
        p = [cos(θ), sin(θ)]
        abs(field(FT, vsol, p)[1] - field_mean(p))
    end
    dists = [minimum(norm(t - p) for p in vsol.fsol.positions) for t in source_pos]
    println("\n$name")
    println("  sources:                    $(length(sources0)) → $(length(vsol.fsol.positions)) retained (true: $N_sources)")
    println("  max relative field error:   $(round(maximum(errs) / field_scale, digits = 4))")
    println("  true source → nearest kept: mean $(round(mean(dists), digits = 3)), max $(round(maximum(dists), digits = 3))")
end

report("ring of candidates + source position M-step", sources_ring, vsol_ring)
report("sources everywhere outside, ARD only", sources_grid, vsol_grid)

# Can ARD alone learn the correct sources? No. ARD is a subset selector: it can only switch
# candidates off, never move them, so the sources it keeps are exactly the grid points it
# started from — and no grid point sits on a true source. The best it can do is spend a
# handful of neighbouring grid points on each true source to synthesise its field, which is
# why it retains roughly three times too many and none of them lands on a true position.
# It is still a good *field* solver: the boundary data are fitted to about the noise level
# (misfit_ratio ≈ 1), and refining the grid tightens the retained cloud around the true ring
# without ever collapsing onto it. Recovering the sources themselves needs the M-step over χ
# of case 1, which turns the discrete choice into a continuous one.
println("\n  misfit_ratio (≈1 means fitted to the noise level): " *
        "ring $(round(vsol_ring.misfit_ratio, digits = 3)), grid $(round(vsol_grid.misfit_ratio, digits = 3))")

println("\nsaved figures to $outdir")
